eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
app:
  microservice:
    portfolio:
      endpoints:
        asset: http://PORTFOLIO-INTERNAL-MS/portfolio/asset
spring:
  datasource:
    username: ${database_username}
    password: ${database_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  profiles:
    active: ${ENV}        

