eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
app:
  microservice:
    portfolio:
      endpoints:
        asset: http://PORTFOLIO-INTERNAL-MS/portfolio/asset      

